### ISSUE TITLE
Remove the osio branch

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/booster-catalog#108]
As per discussion in MM, the osio team is doing their filtering in the tagged versions, hebce making the osio branch not used at all. Remove the branch and update the readme

Cc: @jstrachan  @rawlingsj

**Comment by jstrachan** [comment]
we're doing the filtering in our own addon

**Comment by benoitf** [comment]
FYI we were using that branch [1] to pre-build the samples in rh-che-docker images and now the CI jobs are failing [2]

so, now, how to get the version used on osio ?

[1] https://github.com/redhat-developer/che-dockerfiles/blob/master/recipes/spring-boot/init-maven.sh#L36
[2] https://ci.centos.org/view/Devtools/job/devtools-eclipse-che-build-dockerfiles/

**Comment by gastaldi** [comment]
Hi @benoitf. Use the `v10` tag now. @jstrachan told us that nobody was using that branch, therefore I think it was a communication problem

**Comment by gastaldi** [comment]
@benoitf Here is a PR that should fix this: https://github.com/redhat-developer/che-dockerfiles/pull/25

**Comment by benoitf** [comment]
thanks for the PR, I was fixing it also

**Comment by benoitf** [comment]
@gastaldi I will use v10 but idea with the branch was that we were able to ensure the version used on osio was the same than we built the images.
By using a tag (thx for the workaround),now, we've to know (with a command) which tag is used on osio

**Comment by jstrachan** [comment]
noone was managing the `osio` branch and the `next` branch forge was using broke on us; so we're now using version tags - e.g. `v10` for now - so we can keep up with recent RHOAR quickstarts. 

Am sure we'll have to change again in the future.  At least I now know with docker image to PR next time we change the tag (due to a new RHOAR release of the catalog) - redhat-developer/che-dockerfiles
