### ISSUE TITLE
Add support to map Boosters to Missions

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/booster-catalog#6]
The Booster Catalog currently defines all Boosters; we need it to be able to map the Boosters to Missions such that the UI can show available Boosters after the Mission is selected by the user.

**Comment by gastaldi** [comment]
Here is a suggestion: 

Missions could be listed in the booster-catalog repository in a {{missions.yaml}} file and each booster project could map to existing missions in their {{.openshiftio/booster.yaml}} file by adding a {{missions}} array in that file

**Comment by gastaldi** [comment]
Missions and runtimes are now categorized using the directory structure

**Comment by cescoffier** [comment]
Wouldn't this be an issue when we will have runtime specific missions ?

**Comment by gastaldi** [comment]
@cescoffier what do you mean? Can you give an example?

**Comment by cescoffier** [comment]
For example, if we want to add a mission about gRPC - very Vert.x specific, how would it work? Having a director with a single file ?

**Comment by gastaldi** [comment]
Yeah, in this case it will have a gRPc/vert.x/grpc-vertx-booster.yaml afaik

Em 9 de abr de 2017 14:10, "Clement Escoffier" <notifications@github.com>
escreveu:

For example, if we want to add a mission about gRPC - very Vert.x specific,
how would it work? Having a director with a single file ?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/openshiftio/booster-catalog/issues/6#issuecomment-292798672>,
or mute the thread
